### ISSUE TITLE
v1.5.1: uninitialized constant Chartkick::Engine::Sprockets (NameError)

### ISSUE THREAD

**Issue by baburdick** [ankane/chartkick#256]
v1.5.1 exhibits this error when I attempt to run specs in my app. Down-grading to v1.4.2 resolves the issue.
```
~/.rvm/gems/ruby-2.2.4@my_service/gems/chartkick-1.5.0/lib/chartkick/engine.rb:4:in `block in <class:Engine>': uninitialized constant Chartkick::Engine::Sprockets (NameError)
	from ~/.rvm/gems/ruby-2.2.4@my_service/gems/railties-4.1.15/lib/rails/initializable.rb:30:in `instance_exec'
	from ~/.rvm/gems/ruby-2.2.4@my_service/gems/railties-4.1.15/lib/rails/initializable.rb:30:in `run'
	from ~/.rvm/gems/ruby-2.2.4@my_service/gems/railties-4.1.15/lib/rails/initializable.rb:55:in `block in run_initializers'
	from ~/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from ~/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from ~/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from ~/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from ~/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from ~/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from ~/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from ~/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from ~/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from ~/.rvm/gems/ruby-2.2.4@my_service/gems/railties-4.1.15/lib/rails/initializable.rb:54:in `run_initializers'
	from ~/.rvm/gems/ruby-2.2.4@my_service/gems/railties-4.1.15/lib/rails/application.rb:300:in `initialize!'
	from ~/.rvm/gems/ruby-2.2.4@my_service/gems/railties-4.1.15/lib/rails/railtie.rb:194:in `public_send'
	from ~/.rvm/gems/ruby-2.2.4@my_service/gems/railties-4.1.15/lib/rails/railtie.rb:194:in `method_missing'
	from ~/Code/Integra/my_service/config/environment.rb:5:in `<top (required)>'
	from ~/Code/Integra/my_service/spec/spec_helper.rb:6:in `require'
	from ~/Code/Integra/my_service/spec/spec_helper.rb:6:in `<top (required)>'
	from ~/Code/Integra/my_service/spec/schedules/activate_inactive_phone_numbers_spec.rb:1:in `require'
	from ~/Code/Integra/my_service/spec/schedules/activate_inactive_phone_numbers_spec.rb:1:in `<top (required)>'
	from ~/.rvm/gems/ruby-2.2.4@my_service/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load'
	from ~/.rvm/gems/ruby-2.2.4@my_service/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
	from ~/.rvm/gems/ruby-2.2.4@my_service/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
	from ~/.rvm/gems/ruby-2.2.4@my_service/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
	from ~/.rvm/gems/ruby-2.2.4@my_service/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
	from ~/.rvm/gems/ruby-2.2.4@my_service/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
	from ~/.rvm/gems/ruby-2.2.4@my_service/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from ~/.rvm/gems/ruby-2.2.4@my_service/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from ~/.rvm/gems/ruby-2.2.4@my_service/gems/rspec-core-3.4.4/exe/rspec:4:in `<main>'
```

**Comment by ankane** [comment]
Hi Bruce, thanks for reporting. This should now be fixed on the `master` branch.

**Comment by baburdick** [comment]
Thanks @ankane. I've confirmed that bc8e8c3520d5879a03d57361481ebb56f247dfd9 resolves this issue. Looking forward to the release.

**Comment by ankane** [comment]
Released.
