### ISSUE TITLE
Plain HTML+ERB (Without Framework)

### ISSUE THREAD

**Issue by noraj** [ankane/chartkick#529]
In Apexcharts.rb there is an installation option for [Plain HTML+ERB (Without Framework)](https://github.com/styd/apexcharts.rb#plain-htmlerb-without-framework)

It tried

```erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/chartkick/2.3.0/chartkick.min.js.map"></script>
<% require 'chartkick' %>
<%= pie_chart({"Football" => 10, "Basketball" => 5}) %>
```

```
Traceback (most recent call last):
        5: from /home/noraj/.rbenv/versions/2.7.0/bin/erb:175:in `<main>'
        4: from /home/noraj/.rbenv/versions/2.7.0/bin/erb:154:in `run'
        3: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/2.7.0/erb.rb:890:in `run'
        2: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/2.7.0/erb.rb:905:in `result'
        1: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/2.7.0/erb.rb:905:in `eval'
chartkick.html.erb:4:in `<main>': undefined method `pie_chart' for main:Object (NoMethodError)
```

and

```erb
<% require 'chartkick' %>
<% require 'chart.js' %>
<%= pie_chart({"Football" => 10, "Basketball" => 5}) %>
```

```
Traceback (most recent call last):
        7: from /home/noraj/.rbenv/versions/2.7.0/bin/erb:175:in `<main>'
        6: from /home/noraj/.rbenv/versions/2.7.0/bin/erb:154:in `run'
        5: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/2.7.0/erb.rb:890:in `run'
        4: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/2.7.0/erb.rb:905:in `result'
        3: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/2.7.0/erb.rb:905:in `eval'
        2: from chartkick.html.erb:2:in `<main>'
        1: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/home/noraj/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- chart.js (LoadError)
```

without success.

Of course there is the pure JS version but not using the ruby wrapper.

**Comment by ankane** [comment]
Hey @noraj, non-framework installation isn't officially supported, but you can use similar code:

```erb
<script src="path/to/Chart.bundle.js"></script>
<script src="path/to/chartkick.js"></script>
<% require "chartkick" %>
<% include Chartkick::Helper %>
```
