### ISSUE TITLE
Version 4.0.0 - unable to uglify in Sprockets.

### ISSUE THREAD

**Issue by Cory-Christensen** [ankane/chartkick#563]
**Version**
4.0.0

**Describe the bug**
Uglifier gem is unable to compile `Chart.bundle`. I am compiling using Sprockets, not webpacker.

**Stacktrace**
```** Execute assets:precompile
rails aborted!
Uglifier::Error:
.../uglifier-4.2.0/lib/uglifier.rb:291:in `parse_result'
.../uglifier-4.2.0/lib/uglifier.rb:221:in `run_uglifyjs'
.../uglifier-4.2.0/lib/uglifier.rb:166:in `compile'
.../sprockets-4.0.2/lib/sprockets/compressing.rb:84:in `block in js_compressor='
.../sprockets-4.0.2/lib/sprockets/processor_utils.rb:84:in `call_processor'
.../sprockets-4.0.2/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
.../sprockets-4.0.2/lib/sprockets/processor_utils.rb:65:in `reverse_each'
.../sprockets-4.0.2/lib/sprockets/processor_utils.rb:65:in `call_processors'
.../sprockets-4.0.2/lib/sprockets/loader.rb:182:in `load_from_unloaded'
.../sprockets-4.0.2/lib/sprockets/loader.rb:59:in `block in load'
.../sprockets-4.0.2/lib/sprockets/loader.rb:337:in `fetch_asset_from_dependency_cache'
.../sprockets-4.0.2/lib/sprockets/loader.rb:43:in `load'
.../sprockets-4.0.2/lib/sprockets/cached_environment.rb:44:in `load'
.../sprockets-4.0.2/lib/sprockets/base.rb:81:in `find_asset'
.../sprockets-4.0.2/lib/sprockets/base.rb:88:in `find_all_linked_assets'
.../sprockets-4.0.2/lib/sprockets/manifest.rb:125:in `block (2 levels) in find'
.../concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
.../concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:41:in `block in synchronize'
.../concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
.../concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
.../concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:19:in `execute'
.../concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/promise.rb:563:in `block in realize'
.../concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'
.../concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_worker'
.../concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `loop'
.../concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `block (2 levels) in create_worker'
.../concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `catch'
.../concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block in create_worker'
Tasks: TOP => assets:precompile```

**To reproduce**
Reproducible by running `bundle exec rails assets:precompile --trace`.

Looking into the issue, in the meantime will stick to 3.4.

**Comment by ankane** [comment]
Hey @Cory-Christensen, thanks for reporting! Looks it's due to the vendored `chart.js` file using ES6 syntax. 

```txt
Uglifier::Error: Unexpected token: keyword (const)
```

Will work on a fix.

**Comment by Cory-Christensen** [comment]
Thanks @ankane - massive fan of your work btw, keep it up.

**Comment by ankane** [comment]
Hey @Cory-Christensen, can you give master a shot?

```ruby
gem 'chartkick', github: 'ankane/chartkick'
```

**Comment by Cory-Christensen** [comment]
I can compile the assets successfully now, thanks.

**Comment by ankane** [comment]
Great, just pushed a new release.
